Need to install numpy==1.26.4, bioservices, shap==0.42.0, gprofiler-official

In [1]:
import numpy as np
import shap
import pandas as pd

IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

In [3]:
!which altair

'which' is not recognized as an internal or external command,
operable program or batch file.

In [2]:
import mlmarker

In [2]:
df1 = pd.read_csv('C:\\Users\\tinec\\git\\MLMarker-streamlit\\testsample2.tsv', sep='\t')
df2 = pd.read_csv('C:\\Users\\tinec\\git\\MLMarker-streamlit\\test_tissue_predictor_notfiltered_healthy_2206_20250113.csv')
#only keep the first row of df2
df2 = df2.iloc[0:1, :]
#drop rows in df2 that only contain zero
df2 = df2.loc[(df2 != 0).any(axis=1)]

In [3]:
df1.shape

(14, 11892)

In [5]:
df1

,sample,A0A024RBG1,A0A075B6H7,A0A075B6H8,A0A075B6H9,A0A075B6I0,A0A075B6I1,A0A075B6I7,A0A075B6I9,A0A075B6J1,...,Q9Y6X8,Q9Y6X9,Q9Y6Y0,Q9Y6Y1,Q9Y6Y8,Q9Y6Y9,Q9Y6Z4,Q9Y6Z5,Q9Y6Z7,W5XKT8
0,Small intestine_Diseased,0.0,6.279850e+12,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,9.712835e+10,0.0,0.0,0.0,0.0,0.0
1,Urinary bladder_Cancer,0.0,2.817740e+12,0.000000e+00,0.0,2.679160e+12,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,9.805720e+10,0.0,0.0,0.0,0.0,0.0
2,Hela_Cell culture,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,1.199350e+12,0.000000,0.000000e+00,0.0,1.003860e+12,0.0,0.0,0.0,0.0,0.0
3,Liver_Cell culture,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,2.046140e+11,0.0,1.313620e+12,0.0,0.0,0.0,0.0,0.0
4,Blood plasma_Diseased,0.0,9.772100e+13,3.229530e+12,0.0,6.194340e+12,3.148790e+13,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
5,Lung_Cancer,0.0,2.472100e+12,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
6,Colon_Cancer,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,1.840490e+12,0.0,0.0,0.0,0.0,0.0
7,Ovary_Cancer,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
8,Urine_Diseased,0.0,1.253620e+14,0.000000e+00,0.0,1.589290e+13,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
9,Colon_Cell culture,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,2.370200e+12,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
10,Colon_Extracellular vesicles,0.0,2.864940e+13,0.000000e+00,0.0,6.810110e+12,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
11,Breast_Cancer,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
12,Colon_Cancer,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
13,Pituitary_gland_healthy,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000153,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0

In [7]:
#drop the secon doccurence of Colon_Cancer in df1
df1 = df1.drop_duplicates(subset=['sample'], keep='first')
#drop the Lung_cancer and Breast_cancer
df1 = df1[~df1['sample'].isin(['Lung_Cancer', 'Breast_Cancer'])]
df1.shape

(11, 11892)

In [ ]:
df1.to_csv('testsample2.tsv', sep='\t', index=False)

In [34]:
df1.drop(columns=['Unnamed: 0'], inplace=True)

In [28]:
#add df2 as rows to df1
df = pd.concat([df1, df2], ignore_index=True)
print(df.shape, df1.shape, df2.shape)

(14, 11894) (13, 11892) (1, 5981)

In [29]:
df

,sample,A0A024RBG1,A0A075B6H7,A0A075B6H8,A0A075B6H9,A0A075B6I0,A0A075B6I1,A0A075B6I7,A0A075B6I9,A0A075B6J1,...,Q9Y6Y0,Q9Y6Y1,Q9Y6Y8,Q9Y6Y9,Q9Y6Z4,Q9Y6Z5,Q9Y6Z7,W5XKT8,Unnamed: 0,tissue_name
0,Small intestine_Diseased,0.0,6.279850e+12,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.0,9.712835e+10,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,Urinary bladder_Cancer,0.0,2.817740e+12,0.000000e+00,0.0,2.679160e+12,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.0,9.805720e+10,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,Hela_Cell culture,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.0,1.003860e+12,0.0,0.0,0.0,0.0,0.0,NaN,NaN
3,Liver_Cell culture,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,2.046140e+11,0.0,1.313620e+12,0.0,0.0,0.0,0.0,0.0,NaN,NaN
4,Blood plasma_Diseased,0.0,9.772100e+13,3.229530e+12,0.0,6.194340e+12,3.148790e+13,0.0,0.0,0.0,...,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,NaN,NaN
5,Lung_Cancer,0.0,2.472100e+12,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,NaN,NaN
6,Colon_Cancer,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.0,1.840490e+12,0.0,0.0,0.0,0.0,0.0,NaN,NaN
7,Ovary_Cancer,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,NaN,NaN
8,Urine_Diseased,0.0,1.253620e+14,0.000000e+00,0.0,1.589290e+13,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,NaN,NaN
9,Colon_Cell culture,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,2.370200e+12,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,NaN,NaN
10,Colon_Extracellular vesicles,0.0,2.864940e+13,0.000000e+00,0.0,6.810110e+12,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,NaN,NaN
11,Breast_Cancer,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,NaN,NaN
12,Colon_Cancer,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,NaN,NaN
13,NaN,NaN,0.000000e+00,0.000000e+00,0.0,0.000000e+00,NaN,NaN,0.0,NaN,...,0.000000e+00,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,1289.0,Pituitary gland

In [30]:
#where tissue_name is pituitary gland, fill in the values for index, assay_id, cell_type, disease_status and fluid with 1, 1, 'pituitary gland', 'healthy', 'blood'
df.loc[df['tissue_name'] == 'Pituitary gland', ['sample']] = ['Pituitary_gland_healthy']
#drop columns Unnamed: 0 and tissue_name
df = df.drop(columns=['Unnamed: 0', 'tissue_name'])

df.fillna(0, inplace=True)

df

,sample,A0A024RBG1,A0A075B6H7,A0A075B6H8,A0A075B6H9,A0A075B6I0,A0A075B6I1,A0A075B6I7,A0A075B6I9,A0A075B6J1,...,Q9Y6X8,Q9Y6X9,Q9Y6Y0,Q9Y6Y1,Q9Y6Y8,Q9Y6Y9,Q9Y6Z4,Q9Y6Z5,Q9Y6Z7,W5XKT8
0,Small intestine_Diseased,0.0,6.279850e+12,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,9.712835e+10,0.0,0.0,0.0,0.0,0.0
1,Urinary bladder_Cancer,0.0,2.817740e+12,0.000000e+00,0.0,2.679160e+12,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,9.805720e+10,0.0,0.0,0.0,0.0,0.0
2,Hela_Cell culture,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,1.199350e+12,0.000000,0.000000e+00,0.0,1.003860e+12,0.0,0.0,0.0,0.0,0.0
3,Liver_Cell culture,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,2.046140e+11,0.0,1.313620e+12,0.0,0.0,0.0,0.0,0.0
4,Blood plasma_Diseased,0.0,9.772100e+13,3.229530e+12,0.0,6.194340e+12,3.148790e+13,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
5,Lung_Cancer,0.0,2.472100e+12,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
6,Colon_Cancer,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,1.840490e+12,0.0,0.0,0.0,0.0,0.0
7,Ovary_Cancer,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
8,Urine_Diseased,0.0,1.253620e+14,0.000000e+00,0.0,1.589290e+13,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
9,Colon_Cell culture,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,2.370200e+12,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
10,Colon_Extracellular vesicles,0.0,2.864940e+13,0.000000e+00,0.0,6.810110e+12,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
11,Breast_Cancer,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
12,Colon_Cancer,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000000,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0
13,Pituitary_gland_healthy,0.0,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,...,0.000000e+00,0.000153,0.000000e+00,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0

In [35]:
df1.to_csv('testsample2.tsv', sep='\t', index=False)

In [ ]:
df.to_csv('test')

In [21]:
model = mlmarker.MLMarker(binary=False, dev=True)

Trying to unpickle estimator DecisionTreeClassifier from version 1.5.1 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
Trying to unpickle estimator RandomForestClassifier from version 1.5.1 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations

In [23]:
df = pd.read_csv('C:\\Users\\tinec\\git\\MLMarker-streamlit\\testsample2.tsv', sep='\\t')
df

Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

,sample,A0A024RBG1,A0A075B6H7,A0A075B6H8,A0A075B6H9,A0A075B6I0,A0A075B6I1,A0A075B6I7,A0A075B6I9,A0A075B6J1,...,Q9Y6X8,Q9Y6X9,Q9Y6Y0,Q9Y6Y1,Q9Y6Y8,Q9Y6Y9,Q9Y6Z4,Q9Y6Z5,Q9Y6Z7,W5XKT8
0,Small intestine_Diseased,0,6.279850e+12,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0,0,...,0.000000e+00,0,0.000000e+00,0,9.712835e+10,0,0,0,0,0
1,Urinary bladder_Cancer,0,2.817740e+12,0.000000e+00,0,2.679160e+12,0.000000e+00,0,0,0,...,0.000000e+00,0,0.000000e+00,0,9.805720e+10,0,0,0,0,0
2,Hela_Cell culture,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0,0,...,1.199350e+12,0,0.000000e+00,0,1.003860e+12,0,0,0,0,0
3,Liver_Cell culture,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0,0,...,0.000000e+00,0,2.046140e+11,0,1.313620e+12,0,0,0,0,0
4,Blood plasma_Diseased,0,9.772100e+13,3.229530e+12,0,6.194340e+12,3.148790e+13,0,0,0,...,0.000000e+00,0,0.000000e+00,0,0.000000e+00,0,0,0,0,0
5,Lung_Cancer,0,2.472100e+12,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0,0,...,0.000000e+00,0,0.000000e+00,0,0.000000e+00,0,0,0,0,0
6,Colon_Cancer,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0,0,...,0.000000e+00,0,0.000000e+00,0,1.840490e+12,0,0,0,0,0
7,Ovary_Cancer,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0,0,...,0.000000e+00,0,0.000000e+00,0,0.000000e+00,0,0,0,0,0
8,Urine_Diseased,0,1.253620e+14,0.000000e+00,0,1.589290e+13,0.000000e+00,0,0,0,...,0.000000e+00,0,0.000000e+00,0,0.000000e+00,0,0,0,0,0
9,Colon_Cell culture,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0,0,...,0.000000e+00,0,2.370200e+12,0,0.000000e+00,0,0,0,0,0
10,Colon_Extracellular vesicles,0,2.864940e+13,0.000000e+00,0,6.810110e+12,0.000000e+00,0,0,0,...,0.000000e+00,0,0.000000e+00,0,0.000000e+00,0,0,0,0,0
11,Breast_Cancer,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0,0,...,0.000000e+00,0,0.000000e+00,0,0.000000e+00,0,0,0,0,0
12,Colon_Cancer,0,0.000000e+00,0.000000e+00,0,0.000000e+00,0.000000e+00,0,0,0,...,0.000000e+00,0,0.000000e+00,0,0.000000e+00,0,0,0,0,0

In [30]:
t = model.load_sample(df.iloc[0:1,:])
model.explainability.adjusted_absent_shap_values_df(n_preds=100).T.sum()

tissue
Nasal Polyps       0.17796
Duodenum           0.16472
Small intestine    0.09156
Parotid gland      0.05526
Colon              0.02628
B-cells            0.00303
Liver              0.00919
Testis             0.00380
Ovary              0.00728
Esophagus         -0.00821
Skeletal muscle   -0.02506
Stomach           -0.01121
Adrenal gland     -0.01764
Appendix          -0.01133
Salivary gland    -0.01891
Urinary bladder   -0.01662
Spleen            -0.01683
Oviduct           -0.02081
Lung              -0.02191
Pituitary gland   -0.02268
Brain             -0.02451
Placenta          -0.02585
Tonsil            -0.03505
Endometrium       -0.02476
Rectum            -0.02485
Lymph node        -0.02766
Thyroid           -0.02768
Bone marrow       -0.01311
Kidney            -0.02275
Adipose tissue    -0.02430
Heart             -0.02767
Monocytes         -0.01756
Prostate          -0.02717
Smooth muscle     -0.02901
dtype: float64

In [11]:
import shap

In [12]:
shap.__version__

'0.41.0'